### ISSUE TITLE
Confusion atan2 in the doc

### ISSUE THREAD

**Issue by stla** [AudioSceneDescriptionFormat/asdf#1]
Hello,

  That's still you :-)

  I was taking a look at [this doc](https://audioscenedescriptionformat.readthedocs.io/en/latest/rotation-matrices.html). I think there's a small mistake regarding `atan2`. E.g. it is written `-R[0, 1] / R[1, 1] = tan(alpha)` and then `alpha = atan2(-R[0, 1], R[1, 1])`. The two arguments of `atan2` are reversed (one commonly writes `atan2(y, x)`, not `atan2(x, y)`).

**Comment by stla** [comment]
I've checked and the doc is correct. So there's something I miss.

```python
# -*- coding: utf-8 -*-
from math import pi, sqrt, cos, sin, tan, atan2
import numpy as np
import quaternion

# take a unit quaternion:
q = quaternion.from_rotation_vector([1, 2, 3])

# convert it to a rotation matrix:
R = quaternion.as_rotation_matrix(q)

# roll, elevation, azimuth
roll = atan2(R[2, 2], -R[2, 0])
elevation = asin(R[2, 1])
azimuth = atan2(R[1, 1], -R[0, 1])

roll = atan2(-R[2, 0], R[2, 2])
elevation = asin(R[2, 1])
azimuth = atan2(-R[0, 1], R[1, 1])

Ry = np.array([
    [cos(roll), 0, sin(roll) ],
    [0,         1, 0         ],
    [-sin(roll), 0, cos(roll)]    
])

Rx = np.array([
    [1, 0,              0              ],
    [0, cos(elevation), -sin(elevation)],
    [0, sin(elevation), cos(elevation) ]    
])

Rz = np.array([
    [cos(azimuth), -sin(azimuth), 0],
    [sin(azimuth), cos(azimuth),  0],
    [0,            0,             1]    
])

Rz @ Rx @ Ry

R
```

**Comment by mgeier** [comment]
Thanks for looking into this!

I'm always wary of writing code which isn't tested in some form. This is one of those cases ...

However, it might be correct after all.

You are right that `y` comes before `x` in `atan2()`, but you didn't mention what `y` and `x` actually are.

I wasn't sure either, but I looked it up, and `atan2(y, x)` is meant to compute "the arc tangent of y/x". So the order seems to be `atan2(numerator, denominator)`. Does that make sense?

* SymPy: https://docs.sympy.org/latest/modules/functions/elementary.html#sympy.functions.elementary.trigonometric.atan2
* NumPy: https://numpy.org/doc/stable/reference/generated/numpy.arctan2.html
* C++: https://en.cppreference.com/w/cpp/numeric/math/atan2

**Comment by stla** [comment]
Yes, it seems you're right. I believed during years and years this was the contrary !
Thank you for this doc. Well written. And it contains exactly what I was looking for.

**Comment by mgeier** [comment]
Is there anything I should add to the documentation to avoid confusion?

Or can we close this issue?

**Comment by stla** [comment]
Yes, we can close I think. Sorry for the waste of time.

**Comment by mgeier** [comment]
No problem, it's good to double-check those things!
